### ISSUE TITLE
DB code missing

### ISSUE THREAD

**Issue by subhash909** [Enigma10/E-commerce-jsp-and-servlet-#3]
BC.........
who gives the DB Code

**Comment by Enigma10** [comment]
You could ask it nicely. :-1: .

**Comment by Enigma10** [comment]
Anyway this was done in 2 year before. So i am not sure that i could able to find database in my PC. But I will try.
But if you need shopping-cart app than i have similar project which do in nodejs. I will upload it in night. 
I would recommended you to go for it. it is complete. you just need to download repository.

**Comment by subhash909** [comment]
thnax

and sorry for my word

**Comment by Enigma10** [comment]
https://github.com/Enigma10/Shopping-Cart Added Nodejs repository
